ln -s ~/.config/alacritty alacritty
ln -s ~/.config/btop btop
ln -s ~/.config/cava cava
ln -s ~/.config/corectrl corectrl
ln -s ~/.config/dunst dunst
ln -s ~/.config/eww eww
ln -s ~/.config/fastfetch fastfetch
ln -s ~/.config/fish fish
ln -s ~/.config/fontconfig fontconfig
ln -s ~/.config/foot foot
ln -s ~/.config/geany geany
ln -s ~/.config/goverlay goverlay
ln -s ~/.config/htop htop
ln -s ~/.config/hypr hypr
ln -s ~/.config/hyprland-autoname-workspaces hyprland-autoname-workspaces
ln -s ~/.config/input-remapper-2 input-remapper-2
ln -s ~/.config/kitty kitty
ln -s ~/.config/Kvantum Kvantum
ln -s ~/.config/mako mako
ln -s ~/.config/MangoHud MangoHud
ln -s ~/.config/micro micro
ln -s ~/.config/mpv mpv
ln -s ~/.config/nvim nvim
ln -s ~/.config/OpenRGB OpenRGB
ln -s ~/.config/opensnitch opensnitch
ln -s ~/.config/radeon-profile radeon-profile
ln -s ~/.config/rofi rofi
ln -s ~/.config/swappy swappy
ln -s ~/.config/swaylock swaylock
ln -s ~/.config/swaync swaync
ln -s ~/.config/tabliss tabliss
ln -s ~/.config/Thunar Thunar
ln -s ~/.config/wal wal
ln -s ~/.config/waybar waybar
ln -s ~/.config/wofi wofi
ln -s ~/.config/dolphinrc dolphinrc
ln -s ~/.config/kdeglobals kdeglobals
ln -s ~/.config/konsolerc konsolerc
ln -s ~/.config/starship.toml starship.toml
ln -s ~/.config/yakuakerc yakuakerc